### ISSUE TITLE
Missing dateutil dependency

### ISSUE THREAD

**Issue by mbmccoy** [qnub/django-boto#19]
Summary: django-boto requires on python-dateutil to function properly on python3.4. 

To reproduce, install django-boto using pip on a python3.4 virtualenv:

    >> pip install django-boto
    >> pip freeze
    Django==1.7.1
    boto==2.34.0
    django-boto==0.3.8

Upon running a management command, a dependency error occurs:

    >> ./manage.py makemigrations
    Traceback (most recent call last):
    [... cut for brevity ...]
      File "[path-to-project]/error_reproduce/models.py", line 2, in <module>
        from django_boto.s3.storage import S3Storage
      File "[path-to-virtualenv]/lib/python3.4/site-packages/django_boto/s3/__init__.py", line 3, in <module>
        from .shortcuts import upload, remove, download, get_url
      File "[path-to-vitrualenv]/lib/python3.4/site-packages/django_boto/s3/shortcuts.py", line 4, in <module>
        from .storage import S3Storage
      File "[path-to-vitualenv]/lib/python3.4/site-packages/django_boto/s3/storage.py", line 5, in <module>
        from dateutil.parser import parse as parse_date
    ImportError: No module named 'dateutil'

**Comment by qnub** [comment]
Thanks for you response, sorry for delay. Package updated to 0.3.9.
