### ISSUE TITLE
pip install django-boto fails with FileNotFoundError

### ISSUE THREAD

**Issue by albertvaka** [qnub/django-boto#31]
Looks like it is expecting README.md to be there but it's not.
```
$ pip install -U django-boto
Collecting django-boto
  Using cached django-boto-0.3.10.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-5rocw609/django-boto/setup.py", line 40, in <module>
        README = open(os.path.join(os.path.dirname(__file__), 'README.md')).read()
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-5rocw609/django-boto/README.md'
```

**Comment by swaterfall** [comment]
@albertvaka Did you manage to get around this? I'm having the same problem

**Comment by albertvaka** [comment]
You can tell pip to clone the git repo instead of using the packaged version... It's just a packaging issue. I'm on my phone and I don't remember the exact syntax for it.
